import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";

import { cn } from "@/lib/utils"

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

// https://ui.shadcn.com/docs/installation/next

export const metadata: Metadata = {
    title: "ulu's FACEIT stats",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
    <html lang="en" suppressHydrationWarning>
        <body className={cn("bg-background font-sans antialiased", fontSans.variable)}>
            <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange>
                <Analytics/>
                {children}
            </ThemeProvider></body>
    </html>
    );
}
